project:
  type: website

website:
  title: "SABdata"
  description: "Website"
  site-url: "https://denisberte.github.io/"
  repo-url: https://github.com/DenisBerte/denisberte.github.io
  open-graph: true
  navbar:
    background: "#2A7B88"
    logo: "assets/logo.png"
    search: false
    right:
      - text: "Sobre"
        file: index.qmd
        aria-label: Sobre
      - text: "Publicações"
        file: publicacoes.qmd
        aria-label: Publicações
      - text: "Lattes"
        file: cv.qmd
      - text: "Consultoria"
        file: consultoria.qmd
      - icon: github
        href: https://github.com/DenisBerte
        aria-label: Perfil GitHub
      - icon: envelope
        href: "mailto:denis@sabdata.com.br"
        aria-label: Email
  favicon: "assets/logo.png"
  cookie-consent:
    type: express
    style: headline 
    palette: light
  page-footer: 
    right: |
      Criado com {{< fa brands r-project >}} e [Quarto](https://quarto.org/).<br>


execute: 
  freeze: auto

format:
  html:
    theme: flatly
    toc: false
    link-external-newwindow: true

editor: source
