project:
  type: website

website:
  title: "Denis Berté Sálvia"
  description: "Website pessoal"
  site-url: ""
  repo-url: https://github.com/DenisBerte/denisberte.github.io
  open-graph: true
  navbar:
    background: "#2A7B88"
    logo: "assets/logo.png"
    search: false
    right:
      - text: "Sobre"
        file: index.qmd
        aria-label: Sobre
      - file: publicacoes.qmd
        aria-label: Publicações
      - file: cv.qmd
        text: "CV"
      - file: consultoria.qmd
        aria-label: Consultoria
      - icon: github
        href: https://github.com/DenisBerte
        aria-label: Perfil GitHub 
      - icon: linkedin
        url: "#"
        aria-label: Linkedin
        href: "h"
  
  favicon: "Denis Berté Sálvia"
  cookie-consent:
    type: express
    style: headline 
    palette: light
  page-footer: 
    right: |
      Mit {{< fa brands r-project >}} und [Quarto](https://quarto.org/) erstellt.<br>
      Source Code auf [GitHub](https://github.com/DenisBerte)

execute: 
  freeze: auto

format:
  html:
    theme: 
      light: [flatly, styles.scss]
    toc: false
    link-external-newwindow: true

editor: source

